runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
api_version: 'user_defined'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 0s
- url: /
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /reply
  script: unused
  login: optional
  secure: optional
- url: /login
  script: unused
  login: optional
  secure: optional
- url: /update-vote
  script: unused
  login: optional
  secure: optional
- url: /replytree-chart
  script: unused
  login: optional
  secure: optional
- url: /delete-data
  script: unused
  login: optional
  secure: optional
- url: /delete-one
  script: unused
  login: optional
  secure: optional
- url: /data
  script: unused
  login: optional
  secure: optional
- url: /numcomment-chart
  script: unused
  login: optional
  secure: optional
- url: /commentlang-chart
  script: unused
  login: optional
  secure: optional
- url: /chart
  script: unused
  login: optional
  secure: optional
- url: /edit
  script: unused
  login: optional
  secure: optional
- url: /delete-all
  script: unused
  login: optional
  secure: optional

skip_files: app.yaml
